services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: myresto_db
      POSTGRES_USER: myresto
      POSTGRES_PASSWORD: myresto-2025
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: contacter.myresto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Xr9#tLp!7vQ2zKc
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres